'use strict';
(() => {
  const state=()=>{try{return S}catch{return null}};
  function levelAt(i){const s=state();return Number(s?.zoneLevels?.[i]||0)}
  function totalLevels(){const s=state();return (s?.zoneLevels||[]).reduce((a,b)=>a+Number(b||0),0)}
  function decorate(){const hero=document.querySelector('.hero');if(!hero||hero.querySelector('.nf-city'))return;const city=document.createElement('div');city.className='nf-city';city.setAttribute('aria-hidden','true');city.innerHTML=`<div class="nf-moon"><i></i></div><div class="nf-drone d1">◆</div><div class="nf-drone d2">◆</div><div class="nf-buildings">${Array.from({length:10},(_,i)=>`<i data-b="${i}"><b></b></i>`).join('')}</div><div class="nf-ground"></div>`;hero.appendChild(city);const telemetry=document.createElement('div');telemetry.className='nf-telemetry';telemetry.innerHTML='<span>NETWORK <b id="nfNetwork">12%</b></span><span>AUTOMATION <b id="nfAuto">0%</b></span><span>SECTOR <b id="nfSector">01</b></span>';hero.appendChild(telemetry);update()}
  function update(){const city=document.querySelector('.nf-city');if(!city)return;const s=state(),total=totalLevels();city.querySelectorAll('.nf-buildings>i').forEach((el,i)=>{const lv=levelAt(i%12),h=42+Math.min(118,lv*5+i*4);el.style.setProperty('--h',h+'px');el.style.setProperty('--delay',(-i*.37)+'s');el.classList.toggle('hot',lv>=8)});const net=document.getElementById('nfNetwork'),auto=document.getElementById('nfAuto'),sector=document.getElementById('nfSector');if(net)net.textContent=Math.min(100,12+Math.floor(total*1.7))+'%';if(auto)auto.textContent=Math.min(100,Math.floor(Object.keys(s?.upgrades||{}).length/108*100))+'%';if(sector)sector.textContent=String(Math.max(1,(s?.zoneLevels||[]).filter(v=>v>0).length)).padStart(2,'0')}
  function floatGain(x,y,text='+ CREDIT'){const f=document.createElement('div');f.className='nf-float';f.textContent=text;f.style.left=x+'px';f.style.top=y+'px';document.body.appendChild(f);setTimeout(()=>f.remove(),900)}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const txt=(b.textContent||'').toLowerCase();if(b.classList.contains('primary')&&(/produktion|production|producción|produzione|produção/.test(txt)))floatGain(e.clientX,e.clientY,'+ BOOST');if(/kaufen|buy|compr|acheter/.test(txt))setTimeout(update,40)});
  new MutationObserver(()=>{decorate();update()}).observe(document.getElementById('page'),{childList:true,subtree:true});setInterval(update,900);decorate();
})();