'use strict';
(() => {
  const canvas=document.getElementById('fxCanvas'),ctx=canvas?.getContext('2d'),particles=[];let dpr=Math.min(devicePixelRatio||1,2),audio=null,musicTimer=null,musicEnabled=false,lastMusicState=null;
  const state=()=>{try{return S}catch{return null}};
  function resizeCanvas(){if(!canvas||!ctx)return;dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
  function spawnBurst(x,y,kind='tap'){if(!ctx)return;const count=kind==='reward'?26:kind==='prestige'?42:10,colors=kind==='prestige'?['#ff69e8','#8a7dff','#ffffff']:kind==='reward'?['#ffe56b','#59ffd4','#ffffff']:['#59ffd4','#66a8ff','#9c7dff'];for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=(kind==='tap'?1.2:2.2)+Math.random()*3.7;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:1,size:1.2+Math.random()*3.5,color:colors[i%colors.length],glow:kind!=='tap'})}}
  function drawParticles(){if(ctx){ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.045;p.vx*=.99;p.life-=.018;if(p.life<=0){particles.splice(i,1);continue}ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;if(p.glow){ctx.shadowBlur=16;ctx.shadowColor=p.color}else ctx.shadowBlur=0;ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.shadowBlur=0}requestAnimationFrame(drawParticles)}
  class NeonAudio{constructor(){const AC=window.AudioContext||window.webkitAudioContext;this.ctx=AC?new AC():null;this.master=this.ctx?.createGain();this.sfx=this.ctx?.createGain();this.music=this.ctx?.createGain();if(this.ctx){this.master.gain.value=.72;this.sfx.gain.value=.8;this.music.gain.value=.13;this.sfx.connect(this.master);this.music.connect(this.master);this.master.connect(this.ctx.destination)}}resume(){if(this.ctx?.state==='suspended')this.ctx.resume()}tone(freq=440,dur=.08,type='sine',gain=.14,delay=0,dest=this.sfx){if(!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(dest);o.start(t);o.stop(t+dur+.02)}noise(dur=.08,gain=.05){if(!this.ctx)return;const len=Math.floor(this.ctx.sampleRate*dur),buf=this.ctx.createBuffer(1,len,this.ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();src.buffer=buf;f.type='highpass';f.frequency.value=1200;g.gain.value=gain;src.connect(f);f.connect(g);g.connect(this.sfx);src.start()}click(){this.tone(430,.045,'triangle',.07);this.tone(660,.035,'sine',.045,.018)}nav(){this.tone(330,.045,'sine',.045)}buy(){this.tone(320,.07,'square',.055);this.tone(520,.08,'triangle',.07,.045);this.tone(780,.1,'sine',.075,.09);this.noise(.06,.018)}reward(){[523,659,784,1047].forEach((f,i)=>this.tone(f,.17,'sine',.08,i*.055));this.noise(.11,.028)}error(){this.tone(180,.12,'sawtooth',.045);this.tone(135,.16,'sine',.035,.07)}prestige(){[220,330,440,660,880,1320].forEach((f,i)=>this.tone(f,.35,'sine',.07,i*.07))}startMusic(){if(!this.ctx||musicTimer)return;musicEnabled=true;const progression=[[110,164.8,220],[98,146.8,196],[123.5,185,247],[82.4,123.5,164.8]];let step=0;const play=()=>{if(!musicEnabled)return;const chord=progression[step++%progression.length];chord.forEach((f,i)=>{this.tone(f,2.8,i===0?'sine':'triangle',i===0?.055:.028,i*.03,this.music);this.tone(f*2,1.6,'sine',.012,.18+i*.04,this.music)});this.tone(chord[0]*4,.35,'sine',.012,.45,this.music)};play();musicTimer=setInterval(play,2600)}stopMusic(){musicEnabled=false;if(musicTimer){clearInterval(musicTimer);musicTimer=null}}}
  function ensureAudio(){if(!audio)audio=new NeonAudio();audio.resume();syncMusic()}function soundAllowed(){const s=state();return!s||s.settings?.sound!==false}function syncMusic(){const s=state(),should=!s||s.settings?.music!==false;if(lastMusicState===should)return;lastMusicState=should;if(!audio)return;should?audio.startMusic():audio.stopMusic()}function pulseElement(el){if(!el)return;el.classList.remove('neon-pulse');void el.offsetWidth;el.classList.add('neon-pulse');setTimeout(()=>el.classList.remove('neon-pulse'),420)}
  document.addEventListener('pointerdown',e=>{ensureAudio();if(e.isPrimary)spawnBurst(e.clientX,e.clientY,'tap')},{passive:true});
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;ensureAudio();pulseElement(b);if(!soundAllowed())return;const txt=(b.textContent||'').toLowerCase();if(b.closest('.nav'))audio.nav();else if(txt.includes('prestige')){audio.prestige();spawnBurst(innerWidth/2,innerHeight*.42,'prestige')}else if(txt.includes('abholen')||txt.includes('claim')||txt.includes('reward')||txt.includes('riscatta')||txt.includes('récup')){audio.reward();spawnBurst(e.clientX,e.clientY,'reward')}else if(txt.includes('kaufen')||txt.includes('buy')||txt.includes('compr')||txt.includes('acheter'))audio.buy();else if(b.classList.contains('danger'))audio.error();else audio.click();if(state()?.settings?.vibration!==false&&navigator.vibrate)navigator.vibrate(b.classList.contains('primary')?18:8)});
  const toast=document.getElementById('toast');if(toast)new MutationObserver(()=>{if(toast.classList.contains('show')){const text=(toast.textContent||'').toLowerCase();if(/achievement|collect|reward|belohn|quest|freigesch/.test(text)){ensureAudio();if(soundAllowed())audio.reward();spawnBurst(innerWidth/2,innerHeight*.72,'reward')}}}).observe(toast,{attributes:true,childList:true,subtree:true});
  setInterval(()=>{syncMusic();const badge=document.getElementById('audioState');if(badge){const s=state();badge.textContent=(s?.settings?.music===false?'◌':'♫')+' '+(s?.settings?.sound===false?'MUTE':'LIVE');badge.classList.toggle('muted-audio',s?.settings?.sound===false)}},600);
  function boot(){const overlay=document.getElementById('bootOverlay');if(!overlay)return;setTimeout(()=>overlay.classList.add('boot-ready'),250);setTimeout(()=>overlay.classList.add('boot-hide'),1150);setTimeout(()=>overlay.remove(),1900)}resizeCanvas();addEventListener('resize',resizeCanvas,{passive:true});drawParticles();boot();
})();