extends RefCounted
class_name Localization

var language := "de"
var strings := {
"de": {"game_title":"NEON FORGE","subtitle":"Stadt der Zukunft","credits":"Credits","energy":"Energie","research":"Forschung","cores":"Kerne","per_sec":"/s","produce":"PRODUZIEREN","upgrade":"Upgrades","city":"Stadt","quests":"Quests","collection":"Sammlung","prestige":"Prestige","more":"Mehr","buy":"Kaufen","owned":"Besitzt","locked":"Gesperrt","claim":"Abholen","claimed":"Abgeholt","daily":"Tagesbonus","achievements":"Erfolge","settings":"Einstellungen","stats":"Statistiken","events":"Events","offline":"Offline-Ertrag","offline_body":"Während deiner Abwesenheit wurden %s Credits produziert.","ok":"OK","rebirth":"NEUSTART DURCHFÜHREN","rebirth_hint":"Setzt Credits, Energie, Forschung und normale Upgrades zurück. Permanente Kerne bleiben.","language":"Sprache","sound":"Sound","music":"Musik","vibration":"Vibration","reduce_motion":"Animationen reduzieren","reset":"Spielstand zurücksetzen","reset_confirm":"Wirklich ALLES löschen?","cancel":"Abbrechen","yes_reset":"Ja, löschen","new_unlock":"Freigeschaltet","reward":"Belohnung","event_title":"Quantum Rush","event_desc":"Verdiene Event-Chips durch Produktion. Zeitlich begrenzter Fortschritt.","mission_complete":"Mission abgeschlossen!","collect_found":"Neues Sammlerstück!","prestige_ready":"Prestige bereit","production":"Produktion","level":"Stufe","cost":"Kosten","bonus":"Bonus","playtime":"Spielzeit","total_earned":"Gesamtverdienst","highest_cps":"Höchste Credits/s","prestiges":"Prestiges"},
"en": {"game_title":"NEON FORGE","subtitle":"City of Tomorrow","credits":"Credits","energy":"Energy","research":"Research","cores":"Cores","per_sec":"/s","produce":"PRODUCE","upgrade":"Upgrades","city":"City","quests":"Quests","collection":"Collection","prestige":"Prestige","more":"More","buy":"Buy","owned":"Owned","locked":"Locked","claim":"Claim","claimed":"Claimed","daily":"Daily Reward","achievements":"Achievements","settings":"Settings","stats":"Statistics","events":"Events","offline":"Offline Earnings","offline_body":"While you were away, %s Credits were produced.","ok":"OK","rebirth":"PERFORM REBIRTH","rebirth_hint":"Resets Credits, Energy, Research and normal upgrades. Permanent Cores remain.","language":"Language","sound":"Sound","music":"Music","vibration":"Vibration","reduce_motion":"Reduce motion","reset":"Reset save","reset_confirm":"Really delete EVERYTHING?","cancel":"Cancel","yes_reset":"Yes, delete","new_unlock":"Unlocked","reward":"Reward","event_title":"Quantum Rush","event_desc":"Earn Event Chips through production. Limited-time progression.","mission_complete":"Mission complete!","collect_found":"New collectible!","prestige_ready":"Prestige ready","production":"Production","level":"Level","cost":"Cost","bonus":"Bonus","playtime":"Playtime","total_earned":"Total earned","highest_cps":"Highest Credits/s","prestiges":"Prestiges"},
"fr": {"game_title":"NEON FORGE","subtitle":"Ville du futur","credits":"Crédits","energy":"Énergie","research":"Recherche","cores":"Cœurs","produce":"PRODUIRE","upgrade":"Améliorations","city":"Ville","quests":"Quêtes","collection":"Collection","prestige":"Prestige","more":"Plus","buy":"Acheter","daily":"Récompense quotidienne","achievements":"Succès","settings":"Paramètres","stats":"Statistiques","events":"Événements","ok":"OK","language":"Langue"},
"es": {"game_title":"NEON FORGE","subtitle":"Ciudad del futuro","credits":"Créditos","energy":"Energía","research":"Investigación","cores":"Núcleos","produce":"PRODUCIR","upgrade":"Mejoras","city":"Ciudad","quests":"Misiones","collection":"Colección","prestige":"Prestigio","more":"Más","buy":"Comprar","daily":"Recompensa diaria","achievements":"Logros","settings":"Ajustes","stats":"Estadísticas","events":"Eventos","ok":"OK","language":"Idioma"},
"it": {"game_title":"NEON FORGE","subtitle":"Città del futuro","credits":"Crediti","energy":"Energia","research":"Ricerca","cores":"Nuclei","produce":"PRODUCI","upgrade":"Potenziamenti","city":"Città","quests":"Missioni","collection":"Collezione","prestige":"Prestigio","more":"Altro","buy":"Compra","daily":"Ricompensa giornaliera","achievements":"Obiettivi","settings":"Impostazioni","stats":"Statistiche","events":"Eventi","ok":"OK","language":"Lingua"},
"pt": {"game_title":"NEON FORGE","subtitle":"Cidade do futuro","credits":"Créditos","energy":"Energia","research":"Pesquisa","cores":"Núcleos","produce":"PRODUZIR","upgrade":"Melhorias","city":"Cidade","quests":"Missões","collection":"Coleção","prestige":"Prestígio","more":"Mais","buy":"Comprar","daily":"Recompensa diária","achievements":"Conquistas","settings":"Configurações","stats":"Estatísticas","events":"Eventos","ok":"OK","language":"Idioma"}
}
func t(key:String)->String:
    return strings.get(language, strings["en"]).get(key, strings["en"].get(key,key))
func set_language(code:String): language=code if strings.has(code) else "en"
